"""Add is_global to Pump

Revision ID: 1a61f1153031
Revises: 7e9f2ccbd50d
Create Date: 2026-05-24 11:14:11.171286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a61f1153031'
down_revision: Union[str, Sequence[str], None] = '7e9f2ccbd50d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pump', sa.Column('is_global', sa.Boolean(), nullable=True))
    op.execute('UPDATE pump SET is_global = False WHERE is_global IS NULL')
    op.alter_column('pump', 'is_global', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pump', 'is_global')
    # ### end Alembic commands ###
