"""Add precalculated pump fields

Revision ID: 31e3a1eb5cb5
Revises: 1a61f1153031
Create Date: 2026-05-24 13:24:35.472657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e3a1eb5cb5'
down_revision: Union[str, Sequence[str], None] = '1a61f1153031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pump', sa.Column('coeff_a', sa.Float(), nullable=True))
    op.add_column('pump', sa.Column('coeff_b', sa.Float(), nullable=True))
    op.add_column('pump', sa.Column('coeff_c', sa.Float(), nullable=True))
    op.add_column('pump', sa.Column('max_head_m', sa.Float(), nullable=True))
    op.add_column('pump', sa.Column('max_flow_m3h', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pump', 'max_flow_m3h')
    op.drop_column('pump', 'max_head_m')
    op.drop_column('pump', 'coeff_c')
    op.drop_column('pump', 'coeff_b')
    op.drop_column('pump', 'coeff_a')
    # ### end Alembic commands ###
