"""Add stripe fields

Revision ID: 7e9f2ccbd50d
Revises: 425428b1a31f
Create Date: 2026-03-08 15:58:11.056926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7e9f2ccbd50d'
down_revision: Union[str, Sequence[str], None] = '425428b1a31f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('subscription_tier', sqlmodel.sql.sqltypes.AutoString(), server_default='basic', nullable=False))
    op.add_column('user', sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stripe_customer_id')
    op.drop_column('user', 'subscription_tier')
    # ### end Alembic commands ###
