"""Add subscription fields and SystemLog

Revision ID: a324673aba2b
Revises: 5cbe6403129b
Create Date: 2026-03-03 21:46:49.791454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a324673aba2b'
down_revision: Union[str, Sequence[str], None] = '5cbe6403129b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('systemlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(), server_default='trial', nullable=False))
    op.add_column('user', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('total_access_time_minutes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_access_time_minutes')
    op.drop_column('user', 'subscription_end_date')
    op.drop_column('user', 'subscription_status')
    op.drop_table('systemlog')
    # ### end Alembic commands ###
